version: '3.9'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - "3306:3306"
